//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconBMS.Launcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Platform {
            get {
                return ((bool)(this["Platform"]));
            }
            set {
                this["Platform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMD_ACMI {
            get {
                return ((bool)(this["CMD_ACMI"]));
            }
            set {
                this["CMD_ACMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CMD_WINDOW {
            get {
                return ((bool)(this["CMD_WINDOW"]));
            }
            set {
                this["CMD_WINDOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMD_NOMOVIE {
            get {
                return ((bool)(this["CMD_NOMOVIE"]));
            }
            set {
                this["CMD_NOMOVIE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CMD_EF {
            get {
                return ((bool)(this["CMD_EF"]));
            }
            set {
                this["CMD_EF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int CMD_BW {
            get {
                return ((int)(this["CMD_BW"]));
            }
            set {
                this["CMD_BW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoOverride {
            get {
                return ((bool)(this["NoOverride"]));
            }
            set {
                this["NoOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_RLNWS {
            get {
                return ((bool)(this["Misc_RLNWS"]));
            }
            set {
                this["Misc_RLNWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_TrackIRZ {
            get {
                return ((bool)(this["Misc_TrackIRZ"]));
            }
            set {
                this["Misc_TrackIRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_ExMouseLook {
            get {
                return ((bool)(this["Misc_ExMouseLook"]));
            }
            set {
                this["Misc_ExMouseLook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_OverrideSelfCancel {
            get {
                return ((bool)(this["Misc_OverrideSelfCancel"]));
            }
            set {
                this["Misc_OverrideSelfCancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_MouseCursorAnchor {
            get {
                return ((bool)(this["Misc_MouseCursorAnchor"]));
            }
            set {
                this["Misc_MouseCursorAnchor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Third_WDP {
            get {
                return ((string)(this["Third_WDP"]));
            }
            set {
                this["Third_WDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Third_MC {
            get {
                return ((string)(this["Third_MC"]));
            }
            set {
                this["Third_MC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Third_WC {
            get {
                return ((string)(this["Third_WC"]));
            }
            set {
                this["Third_WC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Third_F4WX {
            get {
                return ((string)(this["Third_F4WX"]));
            }
            set {
                this["Third_F4WX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMD_MONO {
            get {
                return ((bool)(this["CMD_MONO"]));
            }
            set {
                this["CMD_MONO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_SmartScalingOverride {
            get {
                return ((bool)(this["Misc_SmartScalingOverride"]));
            }
            set {
                this["Misc_SmartScalingOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_NaturalHeadMovement {
            get {
                return ((bool)(this["Misc_NaturalHeadMovement"]));
            }
            set {
                this["Misc_NaturalHeadMovement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Misc_PilotModel {
            get {
                return ((bool)(this["Misc_PilotModel"]));
            }
            set {
                this["Misc_PilotModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Third_F4RADAR {
            get {
                return ((string)(this["Third_F4RADAR"]));
            }
            set {
                this["Third_F4RADAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Falcon4.0")]
        public string BMS_Version {
            get {
                return ((string)(this["BMS_Version"]));
            }
            set {
                this["BMS_Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_VR {
            get {
                return ((bool)(this["Misc_VR"]));
            }
            set {
                this["Misc_VR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BMS - Full")]
        public string SelectedKeyFileName {
            get {
                return ((string)(this["SelectedKeyFileName"]));
            }
            set {
                this["SelectedKeyFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeNonOverride {
            get {
                return ((bool)(this["FirstTimeNonOverride"]));
            }
            set {
                this["FirstTimeNonOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Misc_3DClickableCursorFixToCenter {
            get {
                return ((bool)(this["Misc_3DClickableCursorFixToCenter"]));
            }
            set {
                this["Misc_3DClickableCursorFixToCenter"] = value;
            }
        }
    }
}
